import { StoreCatalog, ProductData } from '@/types/business';
import { calculateCostBreakdown, calculateRevenueBreakdown } from './costCalculator';
import { generateAffiliateLink } from './storeDetector';

/**
 * Catálogos predefinidos por tienda para simulación de APIs oficiales
 */
export const STORE_CATALOGS: StoreCatalog[] = [
  {
    store: 'shein',
    categories: ['Ropa de Mujer', 'Ropa de Hombre', 'Accesorios', 'Zapatos', 'Bolsos'],
    products: [
      {
        id: 'sh_001',
        url: 'https://www.shein.com/product-001',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Vestido Floral de Verano',
        price: 29.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400',
        description: 'Hermoso vestido floral perfecto para el verano. Material ligero y cómodo.',
        variants: ['S', 'M', 'L', 'XL'],
        weight: 0.5,
        shippingTime: '15-25 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_001'),
        costBreakdown: calculateCostBreakdown(29.99, 0.5),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(29.99, 0.5)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_002',
        url: 'https://www.shein.com/product-002',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Blusa Casual Estampada',
        price: 19.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1564859228273-274232fdb516?w=400',
        description: 'Blusa casual con estampado moderno, ideal para el día a día.',
        variants: ['S', 'M', 'L'],
        weight: 0.3,
        shippingTime: '15-25 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_002'),
        costBreakdown: calculateCostBreakdown(19.99, 0.3),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(19.99, 0.3)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_003',
        url: 'https://www.shein.com/product-003',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Vestido Rojo Elegante',
        price: 34.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400',
        description: 'Vestido rojo elegante ideal para ocasiones especiales. Corte moderno y favorecedor.',
        variants: ['XS', 'S', 'M', 'L'],
        weight: 0.4,
        shippingTime: '15-25 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_003'),
        costBreakdown: calculateCostBreakdown(34.99, 0.4),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(34.99, 0.4)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_004',
        url: 'https://www.shein.com/product-004',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Conjunto Deportivo de Mujer',
        price: 24.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400',
        description: 'Conjunto deportivo de 2 piezas, cómodo y elástico. Perfecto para yoga o gym.',
        variants: ['S', 'M', 'L', 'XL'],
        weight: 0.6,
        shippingTime: '18-25 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_004'),
        costBreakdown: calculateCostBreakdown(24.99, 0.6),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(24.99, 0.6)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_005',
        url: 'https://www.shein.com/product-005',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Bolso Cruzado de Cuero Sintético',
        price: 22.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400',
        description: 'Bolso cruzado elegante con acabado de cuero sintético. Tamaño perfecto para lo esencial.',
        variants: ['Negro', 'Marrón', 'Beige'],
        weight: 0.4,
        shippingTime: '15-25 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_005'),
        costBreakdown: calculateCostBreakdown(22.99, 0.4),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(22.99, 0.4)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_006',
        url: 'https://www.shein.com/product-006',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Zapatos Casuales de Lona',
        price: 27.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=400',
        description: 'Zapatos casuales de lona, cómodos y versátiles para uso diario.',
        variants: ['35', '36', '37', '38', '39', '40'],
        weight: 0.8,
        shippingTime: '20-25 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_006'),
        costBreakdown: calculateCostBreakdown(27.99, 0.8),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(27.99, 0.8)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_007',
        url: 'https://www.shein.com/product-007',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Collar de Cadena Dorada',
        price: 15.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400',
        description: 'Collar de cadena con baño dorado, estilo minimalista y elegante.',
        variants: ['Único'],
        weight: 0.1,
        shippingTime: '15-20 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_007'),
        costBreakdown: calculateCostBreakdown(15.99, 0.1),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(15.99, 0.1)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_008',
        url: 'https://www.shein.com/product-008',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Camisa Oversize de Hombre',
        price: 32.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400',
        description: 'Camisa oversize de estilo urbano, 100% algodón. Perfecta para look casual.',
        variants: ['M', 'L', 'XL', 'XXL'],
        weight: 0.5,
        shippingTime: '18-25 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_008'),
        costBreakdown: calculateCostBreakdown(32.99, 0.5),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(32.99, 0.5)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_009',
        url: 'https://www.shein.com/product-009',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Gafas de Sol Retro',
        price: 18.50,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400',
        description: 'Gafas de sol con diseño retro, protección UV400. Varios colores disponibles.',
        variants: ['Negro', 'Marrón', 'Rosa'],
        weight: 0.15,
        shippingTime: '15-22 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_009'),
        costBreakdown: calculateCostBreakdown(18.50, 0.15),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(18.50, 0.15)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'sh_010',
        url: 'https://www.shein.com/product-010',
        store: 'shein',
        integrationMethod: 'api',
        title: 'Bufanda de Invierno Suave',
        price: 19.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400',
        description: 'Bufanda de invierno súper suave y cálida. Material de alta calidad.',
        variants: ['Gris', 'Beige', 'Negro', 'Rojo'],
        weight: 0.3,
        shippingTime: '15-25 días',
        affiliateLink: generateAffiliateLink('shein', 'sh_010'),
        costBreakdown: calculateCostBreakdown(19.99, 0.3),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(19.99, 0.3)),
        createdAt: new Date().toISOString()
      }
    ]
  },
  {
    store: 'amazon',
    categories: ['Electrónica', 'Hogar', 'Deportes', 'Libros', 'Juguetes'],
    products: [
      {
        id: 'am_001',
        url: 'https://www.amazon.com/product-001',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Smartwatch Deportivo con GPS',
        price: 89.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
        description: 'Reloj inteligente con monitor de frecuencia cardíaca y GPS integrado.',
        variants: ['Negro', 'Azul', 'Rosa'],
        weight: 0.2,
        shippingTime: '10-20 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_001'),
        costBreakdown: calculateCostBreakdown(89.99, 0.2),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(89.99, 0.2)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_002',
        url: 'https://www.amazon.com/product-002',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Audífonos Bluetooth Inalámbricos',
        price: 45.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
        description: 'Audífonos con cancelación de ruido y batería de larga duración.',
        variants: ['Negro', 'Blanco'],
        weight: 0.3,
        shippingTime: '10-20 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_002'),
        costBreakdown: calculateCostBreakdown(45.99, 0.3),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(45.99, 0.3)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_003',
        url: 'https://www.amazon.com/product-003',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Kindle Paperwhite E-Reader',
        price: 139.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=400',
        description: 'Lector de libros electrónicos con pantalla de 6.8", resistente al agua e iluminación ajustable.',
        variants: ['8GB', '16GB', '32GB'],
        weight: 0.25,
        shippingTime: '7-14 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_003'),
        costBreakdown: calculateCostBreakdown(139.99, 0.25),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(139.99, 0.25)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_004',
        url: 'https://www.amazon.com/product-004',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Cafetera Programable 12 Tazas',
        price: 54.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400',
        description: 'Cafetera automática con temporizador programable, jarra térmica y filtro reutilizable.',
        variants: ['Negro', 'Acero Inoxidable'],
        weight: 2.5,
        shippingTime: '10-18 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_004'),
        costBreakdown: calculateCostBreakdown(54.99, 2.5),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(54.99, 2.5)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_005',
        url: 'https://www.amazon.com/product-005',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Teclado Mecánico RGB Gaming',
        price: 79.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400',
        description: 'Teclado mecánico para gaming con switches Cherry MX, iluminación RGB personalizable.',
        variants: ['Red Switch', 'Blue Switch', 'Brown Switch'],
        weight: 1.2,
        shippingTime: '10-16 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_005'),
        costBreakdown: calculateCostBreakdown(79.99, 1.2),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(79.99, 1.2)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_006',
        url: 'https://www.amazon.com/product-006',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Cámara de Seguridad WiFi HD',
        price: 39.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?w=400',
        description: 'Cámara de seguridad inalámbrica 1080p con visión nocturna, audio bidireccional y detección de movimiento.',
        variants: ['Individual', 'Pack 2', 'Pack 4'],
        weight: 0.4,
        shippingTime: '8-14 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_006'),
        costBreakdown: calculateCostBreakdown(39.99, 0.4),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(39.99, 0.4)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_007',
        url: 'https://www.amazon.com/product-007',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Batidora de Mano Eléctrica',
        price: 34.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400',
        description: 'Batidora de inmersión con 5 velocidades, acero inoxidable y accesorios incluidos.',
        variants: ['Único'],
        weight: 1.0,
        shippingTime: '10-18 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_007'),
        costBreakdown: calculateCostBreakdown(34.99, 1.0),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(34.99, 1.0)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_008',
        url: 'https://www.amazon.com/product-008',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Yoga Mat Antideslizante Premium',
        price: 29.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400',
        description: 'Esterilla de yoga de 6mm, material ecológico, antideslizante con bolsa de transporte.',
        variants: ['Púrpura', 'Azul', 'Rosa', 'Negro'],
        weight: 1.5,
        shippingTime: '12-20 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_008'),
        costBreakdown: calculateCostBreakdown(29.99, 1.5),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(29.99, 1.5)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_009',
        url: 'https://www.amazon.com/product-009',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Set de Sartenes Antiadherentes 3 Piezas',
        price: 59.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1556910585-bb4de1ce273c?w=400',
        description: 'Juego de 3 sartenes antiadherentes de cerámica, apto para todo tipo de cocinas.',
        variants: ['Gris', 'Rojo'],
        weight: 3.0,
        shippingTime: '10-18 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_009'),
        costBreakdown: calculateCostBreakdown(59.99, 3.0),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(59.99, 3.0)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'am_010',
        url: 'https://www.amazon.com/product-010',
        store: 'amazon',
        integrationMethod: 'api',
        title: 'Mouse Inalámbrico Ergonómico',
        price: 24.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400',
        description: 'Mouse inalámbrico con diseño ergonómico, 6 botones programables y batería recargable.',
        variants: ['Negro', 'Gris'],
        weight: 0.2,
        shippingTime: '8-14 días',
        affiliateLink: generateAffiliateLink('amazon', 'am_010'),
        costBreakdown: calculateCostBreakdown(24.99, 0.2),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(24.99, 0.2)),
        createdAt: new Date().toISOString()
      }
    ]
  },
  {
    store: 'aliexpress',
    categories: ['Electrónica', 'Hogar', 'Moda', 'Deportes', 'Belleza'],
    products: [
      {
        id: 'al_001',
        url: 'https://www.aliexpress.com/product-001',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Lámpara LED Inteligente RGB',
        price: 34.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400',
        description: 'Lámpara LED con control remoto y múltiples modos de color.',
        variants: ['Blanco', 'Negro'],
        weight: 0.8,
        shippingTime: '25-40 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_001'),
        costBreakdown: calculateCostBreakdown(34.99, 0.8),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(34.99, 0.8)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_002',
        url: 'https://www.aliexpress.com/product-002',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Set de Herramientas Multipropósito',
        price: 24.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=400',
        description: 'Set completo de herramientas para el hogar con estuche incluido.',
        variants: ['Estándar'],
        weight: 1.5,
        shippingTime: '25-40 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_002'),
        costBreakdown: calculateCostBreakdown(24.99, 1.5),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(24.99, 1.5)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_003',
        url: 'https://www.aliexpress.com/product-003',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Funda de Silicona para Celular',
        price: 5.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400',
        description: 'Funda protectora de silicona suave compatible con múltiples modelos. Varios colores disponibles.',
        variants: ['iPhone 13', 'iPhone 14', 'Samsung S23', 'Xiaomi 13'],
        weight: 0.1,
        shippingTime: '20-35 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_003'),
        costBreakdown: calculateCostBreakdown(5.99, 0.1),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(5.99, 0.1)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_004',
        url: 'https://www.aliexpress.com/product-004',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Organizador de Escritorio Multifuncional',
        price: 18.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1509395062183-67c5ad6faff9?w=400',
        description: 'Organizador de escritorio con múltiples compartimentos para oficina o estudio.',
        variants: ['Blanco', 'Negro', 'Rosa', 'Azul'],
        weight: 0.7,
        shippingTime: '22-38 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_004'),
        costBreakdown: calculateCostBreakdown(18.99, 0.7),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(18.99, 0.7)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_005',
        url: 'https://www.aliexpress.com/product-005',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Cable USB-C Carga Rápida 3 metros',
        price: 8.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400',
        description: 'Cable USB-C de 3 metros con soporte para carga rápida hasta 100W. Trenzado reforzado.',
        variants: ['Negro', 'Blanco', 'Rojo'],
        weight: 0.15,
        shippingTime: '20-35 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_005'),
        costBreakdown: calculateCostBreakdown(8.99, 0.15),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(8.99, 0.15)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_006',
        url: 'https://www.aliexpress.com/product-006',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Set de Pinceles de Maquillaje 12 Piezas',
        price: 14.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400',
        description: 'Set profesional de 12 pinceles de maquillaje con cerdas sintéticas suaves. Incluye estuche.',
        variants: ['Rosa', 'Negro', 'Multicolor'],
        weight: 0.3,
        shippingTime: '25-40 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_006'),
        costBreakdown: calculateCostBreakdown(14.99, 0.3),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(14.99, 0.3)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_007',
        url: 'https://www.aliexpress.com/product-007',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Tira LED RGB 5 Metros',
        price: 16.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1566665620958-6e0c533a00fe?w=400',
        description: 'Tira de luces LED RGB de 5 metros con control remoto y app móvil. Fácil instalación.',
        variants: ['5m', '10m', '15m'],
        weight: 0.5,
        shippingTime: '22-38 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_007'),
        costBreakdown: calculateCostBreakdown(16.99, 0.5),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(16.99, 0.5)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_008',
        url: 'https://www.aliexpress.com/product-008',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Banda Elástica de Resistencia para Ejercicio',
        price: 12.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?w=400',
        description: 'Set de 5 bandas de resistencia de diferentes niveles para entrenamiento en casa.',
        variants: ['Set 5 piezas', 'Set 11 piezas'],
        weight: 0.6,
        shippingTime: '25-40 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_008'),
        costBreakdown: calculateCostBreakdown(12.99, 0.6),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(12.99, 0.6)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_009',
        url: 'https://www.aliexpress.com/product-009',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Soporte Giratorio para Tablet/Celular',
        price: 9.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1624823183493-ed5832f48f18?w=400',
        description: 'Soporte ajustable 360° para tablets y celulares. Base antideslizante y plegable.',
        variants: ['Negro', 'Blanco', 'Plata'],
        weight: 0.4,
        shippingTime: '20-35 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_009'),
        costBreakdown: calculateCostBreakdown(9.99, 0.4),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(9.99, 0.4)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_010',
        url: 'https://www.aliexpress.com/product-010',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Báscula Digital de Cocina',
        price: 19.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1584900797129-fb9d9b48c03f?w=400',
        description: 'Báscula digital de precisión hasta 5kg con pantalla LCD. Función de tara y múltiples unidades.',
        variants: ['Blanco', 'Negro', 'Acero Inoxidable'],
        weight: 0.5,
        shippingTime: '25-40 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_010'),
        costBreakdown: calculateCostBreakdown(19.99, 0.5),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(19.99, 0.5)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_011',
        url: 'https://www.aliexpress.com/product-011',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Cargador Inalámbrico Rápido 15W',
        price: 13.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1591290619762-c588dc76e50b?w=400',
        description: 'Base de carga inalámbrica rápida compatible con iPhone y Android. Diseño minimalista.',
        variants: ['Negro', 'Blanco'],
        weight: 0.2,
        shippingTime: '22-38 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_011'),
        costBreakdown: calculateCostBreakdown(13.99, 0.2),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(13.99, 0.2)),
        createdAt: new Date().toISOString()
      },
      {
        id: 'al_012',
        url: 'https://www.aliexpress.com/product-012',
        store: 'aliexpress',
        integrationMethod: 'api',
        title: 'Gorra Deportiva con Protección UV',
        price: 11.99,
        currency: 'USD',
        image: 'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=400',
        description: 'Gorra deportiva de secado rápido con protección UV. Ajustable y transpirable.',
        variants: ['Negro', 'Gris', 'Azul', 'Blanco'],
        weight: 0.2,
        shippingTime: '20-35 días',
        affiliateLink: generateAffiliateLink('aliexpress', 'al_012'),
        costBreakdown: calculateCostBreakdown(11.99, 0.2),
        revenueBreakdown: calculateRevenueBreakdown(calculateCostBreakdown(11.99, 0.2)),
        createdAt: new Date().toISOString()
      }
    ]
  }
];

/**
 * Busca productos en los catálogos simulados
 */
export function searchInCatalogs(
  query: string,
  store?: string,
  category?: string
): ProductData[] {
  let allProducts: ProductData[] = [];

  // Recopilar todos los productos
  STORE_CATALOGS.forEach(catalog => {
    if (!store || catalog.store === store) {
      allProducts = [...allProducts, ...catalog.products];
    }
  });

  // Filtrar por búsqueda
  if (query) {
    const queryLower = query.toLowerCase();
    allProducts = allProducts.filter(p => 
      p.title.toLowerCase().includes(queryLower) ||
      p.description.toLowerCase().includes(queryLower)
    );
  }

  return allProducts;
}

/**
 * Obtiene productos por categoría
 */
export function getProductsByCategory(store: string, category: string): ProductData[] {
  const catalog = STORE_CATALOGS.find(c => c.store === store);
  if (!catalog) return [];
  
  // En una implementación real, aquí filtraríamos por categoría
  // Por ahora retornamos todos los productos de la tienda
  return catalog.products;
}
